<?php

namespace ProductLineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMachineRepository extends EntityRepository
{
}
